import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  safeAreaView: { flex: 1, backgroundColor: "#FFFFFF" },
  scrollView: { flex: 1, backgroundColor: "#F6F9F9", paddingTop: 7 },
  headerContainer: { flexDirection: "row", alignItems: "flex-start", marginBottom: 5, marginHorizontal: 23 },
  headerImageSmall: { width: 26, height: 10, marginTop: 15 },
  headerImageLarge: { width: 15, height: 11, marginTop: 15, marginRight: 11 },
  headerRounded: { width: 113, height: 32, backgroundColor: "#040325", borderRadius: 100, marginRight: 36 },
  headerLine: { width: 2, backgroundColor: "#040325", borderRadius: 1, marginRight: 2 },
  headerIndicatorOuter: { width: 18, borderColor: "#040325", borderRadius: 3, borderWidth: 1, paddingHorizontal: 2, marginTop: 16, marginRight: 1 },
  headerIndicatorInner: { height: 7, backgroundColor: "#040325", borderRadius: 3, marginTop: 1 },
  headerDot: { width: 1, height: 2, backgroundColor: "#040325", marginTop: 19 },
  largeImage: { height: 52 },
  searchBarContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
    marginHorizontal: 20,
  },
  searchBarBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    paddingHorizontal: 10,
    marginTop: 10,
    width: "80%", 
  },
  searchBarIconWrapper: {
    width: 40,
    height: 40,  
    backgroundColor: "#00B0B9",
    borderRadius: 10, 
    justifyContent: "center", 
    alignItems: "center",  
    marginRight: 10,
    marginTop: 8,
    marginBottom: 8,
  },
  searchInput: {
    color: "#738AA0",
    fontSize: 16,
    flex: 1, 
    paddingVertical: 5,
  },
  
  iconWrapper: { width: 50, backgroundColor: "#FFFFFF", borderRadius: 10, paddingHorizontal: 13 },
  icon: { height: 24, marginTop: 13 },
  buttonRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 32, marginHorizontal: 6 },
  mainButton: { width: 141, flexDirection: "row", justifyContent: "center", alignItems: "center", backgroundColor: "#00B0B9", borderRadius: 10, paddingVertical: 10 },
  buttonIcon: { width: 24, height: 24, marginRight: 11 },
  mainButtonText: { color: "#0B1D2D", fontSize: 14 },
  productContainer: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 21, marginHorizontal: 22 },
  productBox: { width: 160, backgroundColor: "#FFFFFF", borderRadius: 10, paddingBottom: 18 },
  productImageContainer: { backgroundColor: "#FFFFFF", paddingLeft: 130, paddingRight: 14, marginBottom: 13 },
  productImage: { width: 16, height: 16, marginTop: 114 },
  productName: { color: "#738AA0", fontSize: 10, marginBottom: 14, marginLeft: 14 },
  productPrice: { color: "#0B1D2D", fontSize: 14, marginLeft: 14 },
  footerContainer: { backgroundColor: "#FFFFFF", borderRadius: 10, paddingVertical: 14, paddingHorizontal: 25, marginBottom: 11, marginHorizontal: 16 },
  footerRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  footerItem: { alignItems: "center", flex: 1 },
  footerIcon: { width: 24, height: 24, marginBottom: 3 },
  footerText: { color: "#738AA0", fontSize: 9 },
  footerTextActive: { color: "#00B0B9", fontSize: 9 },
  flex1: { flex: 1 },
});

export default styles;
