export enum StatusItem {
  AVAILABLE = "AVAILABLE",
  SOLD = "SOLD",
  IN_EXCHANGE = "IN_EXCHANGE",
  EXPIRED = "EXPIRED",
  NO_LONGER_FOR_EXCHANGE = "NO_LONGER_FOR_EXCHANGE",
  PENDING = "PENDING",
  REJECTED = "REJECTED",
}
