export enum TypeNotification {
  CHAT_MESSAGE = "CHAT_MESSAGE",
  UPLOAD_ITEM = "UPLOAD_ITEM",
  EXCHANGE_REQUEST = "EXCHANGE_REQUEST",
  ITEM_EXPIRED = "ITEM_EXPIRED",
  REPORT_RESPONSE = "REPORT_RESPONSE",
  REPORT_HANDLED = "REPORT_HANDLED",
}
