export enum TypeItem {
    KITCHEN_APPLIANCES = "KITCHEN_APPLIANCES",
    CLEANING_LAUNDRY_APPLIANCES= "CLEANING_LAUNDRY_APPLIANCES",
    COOLING_HEATING_APPLIANCES= "COOLING_HEATING_APPLIANCES",
    ELECTRONICS_ENTERTAINMENT_DEVICES= "ELECTRONICS_ENTERTAINMENT_DEVICES",
    LIGHTING_SECURITY_DEVICES= "LIGHTING_SECURITY_DEVICES",
    BEDROOM_APPLIANCES= "BEDROOM_APPLIANCES",
    LIVING_ROOM_APPLIANCES= "LIVING_ROOM_APPLIANCES",
    BATHROOM_APPLIANCES= "BATHROOM_APPLIANCES",
    NO_TYPE = "NO"
  }
  


